name: S3 Upload Artifact
description: Upload artifacts to Amazon S3.
author: blakjak44@gmail.com

branding:
  color: orange
  icon: arrow-up-circle

inputs:
  aws_access_key_id:
    required: false
    type: string
    description: AWS access key ID to access the bucket (if required).
  aws_secret_access_key:
    required: false
    type: string
    description: AWS secret access key to access the bucket (if required).
  aws_region:
    required: false
    type: string
  bucket:
    required: true
    type: string
  scope:
    required: false
    type: string
    default: run
    description: The artifact scope. Can be either "run" or "global". Defaults to "run".
  name:
    required: false
    type: string
    default: artifact
  path:
    required: true
    type: string

runs:
  using: 'node16'
  main: 'dist/index.js'
